name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  call-workflow-in-public-repo:
    uses: eurotech/add-ons-automation/.github/workflows/_shared-backport.yml@main
