name: "Build & Deploy docs"

on:
  push:
    branches:
      - 'docs-develop'
      - 'docs-release-*.*'

jobs:
  Call remote workflow:
    uses: eurotech/add-ons-automation/.github/workflows/_shared-build-deploy-docs.yml@main
