name: "Build & Deploy docs"

on:
  push:
    branches:
      - 'docs-develop'
      - 'docs-release-*.*'

jobs:
  call-workflow-in-public-repo:
    uses: eurotech/add-ons-automation/.github/workflows/_shared-build-deploy-docs.yml@main
    with:
      uptick_config: ${{ inputs.uptick_config }}
