name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  call-workflow-in-public-repo:
    uses: eurotech/add-ons-automation/workflows/pr-lint/action@main
