name: "Release Notes automation"

on:
  workflow_dispatch:
    inputs:
        starting_commit:
          type: string
          description: Commit from which to start generating the release notes
          required: true

jobs:
  call-workflow-in-public-repo:
    uses: eurotech/add-ons-automation/.github/workflows/_shared-release-notes.yml@main
    with:
      starting_commit: ${{ inputs.starting_commit }}
