name: "Build & Deploy docs (shared)"

on: workflow_call

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install setuptools below v72.0.0
        run: python -m pip install 'setuptools<72.0.0'

      - name: Install MkDocs dependencies
        run: pip install -r requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy with mike
        run: mike deploy --push ${GITHUB_REF#refs/heads/}
