name: "Version uptick automation (shared)"

on:
  workflow_call:
    inputs:
        target_branch:
          type: string
          default: 'develop'
          required: true
        uptick_config:
          type: string
          required: true

jobs:
  uptick:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.target_branch }}

    - name: Download ESF version upticker tool
      uses: carlosperate/download-file-action@v1
      with:
        file-url: https://kura-repo.s3.us-west-2.amazonaws.com/esf_upticker_tool/version-uptick-0.1.0-linux-x86_64

    - name: Download desired upticker configuration file
      uses: carlosperate/download-file-action@v1
      with:
        file-url: https://raw.githubusercontent.com/eurotech/add-ons-automation/main/config/version_uptick/${{ inputs.uptick_config }}

    - name: Make the uptick tool executable
      run: |
        chmod +x ./version-uptick-0.1.0-linux-x86_64
      shell: bash

    - name: Run the uptick tool
      run: |
        ./version-uptick-0.1.0-linux-x86_64 \
        --commit --trace process-versions \
        --config-path ${{ inputs.uptick_config }} \
        --root-dir .
      shell: bash

    - name: Cleanup
      run: |
        rm ./version-uptick-0.1.0-linux-x86_64 \
        ${{ inputs.uptick_config }}
      shell: bash

    - name: Get version
      id: get-version
      run: "echo \"resolved-version=\
        $(mvn
          --file ./pom.xml
          -Dexec.executable=echo
          -Dexec.args='${project.version}'
          --quiet exec:exec --non-recursive
        )\" >> \"${GITHUB_OUTPUT}\""
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "chore: automated uptick to ${{ steps.get-version.outputs.resolved-version }}"
        commit-message: "chore: automated uptick to ${{ steps.get-version.outputs.resolved-version }}"
        body: |
          Automated changes by [_Version uptick automation_](https://github.com/eurotech/add-ons-automation/blob/main/.github/workflows/_shared-version-uptick.yml) action.
          - Automated uptick to ${{ steps.get-version.outputs.resolved-version }} version.
          - Automation ran using `${{ inputs.uptick_config }}` configuration.
        branch-suffix: short-commit-hash
