name: "Repository First Time Setup automation (shared)"

on:
  workflow_call:
    inputs:
        esf_version:
          type: string
          default: 'https://changeme'
          required: true
        groupId:
          type: string
          default: ''
          required: true
        artifactId:
          type: string
          default: ''
          required: true

jobs:
  init:
    runs-on: ubuntu-latest
    steps:

    - name: Download ESF archetype
      uses: carlosperate/download-file-action@v1
      with:
        file-url: ${{ github.event.inputs.esf_version }}
      if: startsWith(${{ github.event.inputs.esf_version }}, 'https://eth-repo.s3.amazonaws.com/esf')

    - name: Run the maven install
      run: |
        mvn install:install-file -Dfile=esf-addon-archetype-${{ github.event.inputs.esf_version }}.jar \
        -DgroupId=com.eurotech.framework -DartifactId=esf-addon-archetype \
        -Dversion=${{ github.event.inputs.esf_version }} -Dpackaging=jar
      shell: bash

    - name: Run the maven archetype generate
      run: |
        mvn archetype:generate -B -DarchetypeArtifactId=esf-addon-archetype \
        -DarchetypeGroupId=com.eurotech.framework -DarchetypeVersion="${{ github.event.inputs.esf_version }}" \
        -DgroupId=${{ github.event.inputs.groupId }} -DartifactId=${{ github.event.inputs.artifactId }}
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "chore: Repository initialization from ESF archetype"
        commit-message: "chore: Repository initialization from ESF archetype"
        body: "Automated changes for repository initialization from ESF archetype version ${{ github.event.inputs.esf_version }}"
        branch-suffix: short-commit-hash
