name: "Release Notes automation (shared)"

on:
  workflow_call:
    inputs:
        starting_commit:
          type: string
          required: true

jobs:
  main:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Get version
      id: get-version
      run: "echo \"resolved-version=\
        $(mvn
          --file ./pom.xml
          -Dexec.executable=echo
          -Dexec.args='${project.version}'
          --quiet exec:exec --non-recursive
        )\" >> \"${GITHUB_OUTPUT}\""
      shell: bash

    - name: Get project name
      id: get-project-name
      run: "echo \"resolved-name=\
        $(mvn
          --file ./pom.xml
          -Dexec.executable=echo
          -Dexec.args='${project.name}'
          --quiet exec:exec --non-recursive
        )\" >> \"${GITHUB_OUTPUT}\""
      shell: bash

    - name: Download git-changelog-command-line tool
      id: download-changelog-cli
      uses: carlosperate/download-file-action@v1
      with:
        file-url: https://repo1.maven.org/maven2/se/bjurr/gitchangelog/git-changelog-command-line/1.100.2/git-changelog-command-line-1.100.2.jar
        md5: 09d5fc8b57b3fa9adb94c8d207630cfc

    - name: Download release notes template
      uses: carlosperate/download-file-action@v1
      with:
        file-url: https://raw.githubusercontent.com/eurotech/add-ons-automation/main/config/release_notes/template.hbs

    - name: Download release notes helper
      uses: carlosperate/download-file-action@v1
      with:
        file-url: https://raw.githubusercontent.com/eurotech/add-ons-automation/main/config/release_notes/helper.hbs

    - name: Generate Release Notes
      env:
        COMMIT_START: ${{ github.event.inputs.starting_commit }}
      run: |
        if [[ ! "$COMMIT_START" =~ ^[a-zA-Z0-9]{40}$ ]]
        then
          printf "Error!  Not a valid Git commit hash.\n"
          exit 1
        else
          printf "Git commit hash is valid.\n"
        fi

        java -jar ${{ steps.download-changelog-cli.outputs.file-path }} \
        -fc "$COMMIT_START" \
        -ex "{\"version\":\"${{ steps.get-version.outputs.resolved-version }}\", \"name\":\"${{ steps.get-project-name.outputs.resolved-name}}\"}" \
        -t ./template.hbs \
        -hhf ./helper.hbs \
        -of ./RELEASE_NOTES.txt

    - name: Cleanup
      run: |
        rm ./template.hbs ./helper.hbs ${{ steps.download-changelog-cli.outputs.file-path }}
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "chore: add ${{ steps.get-version.outputs.resolved-version }} release notes"
        commit-message: "chore: add ${{ steps.get-version.outputs.resolved-version }} release notes"
        body: |
           Automated changes by [_Release Notes automation_](https://github.com/eurotech/add-ons-automation/blob/main/.github/workflows/_shared-release-notes.yml) action.
           - Add ${{ steps.get-version.outputs.version }} version release notes since commit `${{ github.event.inputs.starting_commit }}` (non-inclusive).
        branch-suffix: short-commit-hash
